# Syntax reference for this file:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: sphinx
on: [push, pull_request]

# https://gist.github.com/c-bata/ed5e7b7f8015502ee5092a3e77937c99
jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build Sphinx docs
        run: |
          make html

      # https://github.com/marketplace/actions/github-pages
      - if: success()
        uses: crazy-max/ghaction-github-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: _build/html/


# This action probably does everything for you:
# https://github.com/marketplace/actions/sphinx-build